services:
  - type: web
    name: news-summarizer-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn news_summarizer.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: news_summarizer.settings
      - key: DJANGO_SECRET_KEY
        sync: false   # Set value directly in Render dashboard, not here!
      - key: DJANGO_ALLOWED_HOSTS
        value: news-summarizer-backend-zgiq.onrender.com,localhost,127.0.0.1,https://news-summarizer-ai.onrender.com
      - key: DJANGO_DEBUG
        value: "False"
      - key: DATABASE_URL
        value: sqlite:///db.sqlite3
      - key: CELERY_BROKER_URL
        value: redis://localhost:6379/0
      - key: CELERY_RESULT_BACKEND
        value: django-db
    autoDeploy: true
    staticPublishPath: staticfiles