services:
  - type: web
    name: news-summarizer-backend
    env: python
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: gunicorn news_summarizer.wsgi:application --chdir backend
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: news_summarizer.settings
      - key: DJANGO_SECRET_KEY
        sync: false
      - key: DJANGO_ALLOWED_HOSTS
        value: news-summarizer-backend-zgiq.onrender.com,localhost,127.0.0.1
      - key: DJANGO_DEBUG
        value: "False"
      - key: DATABASE_URL
        value: sqlite:///db.sqlite3
      - key: CELERY_BROKER_URL
        value: redis://localhost:6379/0
      - key: CELERY_RESULT_BACKEND
        value: django-db
    autoDeploy: true
    staticPublishPath: backend/staticfiles
