# Generated by Django 5.2.4 on 2025-07-21 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=512)),
                ("fake_news_label", models.CharField(max_length=16)),
                ("user_feedback", models.CharField(max_length=16)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="queryhistory",
            name="user",
        ),
        migrations.AlterField(
            model_name="queryhistory",
            name="fake_news_label",
            field=models.CharField(max_length=16),
        ),
    ]
