# Generated by Django 5.2.4 on 2025-07-21 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_feedback_remove_queryhistory_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="queryhistory",
            name="duration_ms",
            field=models.IntegerField(default=0),
        ),
    ]
